#!/bin/bash
# Save as Evidence.sh
# script to add a file to an evidence list with optional comment
# by John Lehr (c) 2009

TITLE="Save as Evidence"

# create evidence directory on desktop
mkdir -p $HOME/Desktop/Evidence

# obtain optional user comment about evidence item
COMMENT=$(zenity --entry \
	--title "$TITLE" \
	--text "Investigator's note (optional, \"Cancel\" quits):" \
	--width=500)

# gather data for evidence report
echo "$NAUTILUS_SCRIPT_SELECTED_URIS" | \
	while read URI; do
		FILENAME="$(echo $URI | sed 's/file:\/\///' | sed 's/\%20/ /g')"  #filename must be determined by URI in Nautilus for virtual folders such as search results
		#NEW_FILENAME="$(echo $FILENAME | sed 's/\//^/g')"  #renaming the file with the full path leads to files with names longer than 255 characters
		NEW_FILENAME="$(stat -L -c %n $FILENAME)-$(stat -L -c %i $FILENAME)"  #file renamed with "basename-inode number"

		FILE_STAT="$(stat -L "$FILENAME")"
		MD5="$(md5sum "$FILENAME" | cut -d " " -f1)"
		FILE_TYPE="$(file -bL "$FILENAME")"

		echo -e "$FILE_STAT\n\nFile Type: $FILE_TYPE\n\nMD5 HASH: $MD5\n\nInvestigator's Note: $COMMENT" > "$HOME/Desktop/Evidence/$NEW_FILENAME.stats.txt"

		cp "$FILENAME" "$HOME/Desktop/Evidence/$NEW_FILENAME"
	done

exit 0
