#!/bin/bash
#Find Images Here
#script to find images by file magic and create symlinks in one directory
#by John Lehr (c) 2009

TEMP_DIR=$(mktemp -d)
nautilus $TEMP_DIR;

find "$(pwd)" -type f | tee \
	>(sleep 3; zenity --progress --title="Find Images" --text="Searching..." --pulsate  --auto-close --auto-kill) \
	>(while read FILENAME; do
		IMAGE="$(file -bi "$FILENAME" | grep image)"
		if [ "$IMAGE" != "" ]; then
			NEW_FILENAME="$(echo "$FILENAME" | sed 's/\//^/g')"
			ln -s -T "$FILENAME" "$TEMP_DIR/$NEW_FILENAME"
		fi
	done)
		
exit 0
