#!/bin/bash
#Find Images Here
#by John Lehr (c) 2009

TITLE="Show Images"
TEMP_DIR=$(mktemp -d)
SEARCH_DIR=$(pwd)

cd $TEMP_DIR 
nautilus $TEMP_DIR;

find "$SEARCH_DIR" -type f | \
	while read FILENAME; do
		IMAGE=$(file -bi "$FILENAME" | grep image)
		if [ "$IMAGE" != "" ]; then
			NEW_FILENAME=$(echo "$FILENAME" | tr '/' '_')
			ln -s -T "$FILENAME" "$NEW_FILENAME"
		fi
	done
		
exit 0
