#!/bin/bash
# Show SQLite3 Tables
# by John Lehr (c) 2009

# variables
TITLE="Show Tables"

# list tables in information box
TABLES=$(echo -e "Tables in Database:\n\n$(sqlite3 $@ ".table" | tr -s ' ' '\n ')")
zenity --info \
	--title "$TITLE" \
	--text "$TABLES" 

exit 0
