#!/bin/bash
#Show Nautilus Variables
#by J. Lehr (c) 2009

TEXT=$(echo -e "Selected File Paths: $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS\n\nSelected URI's: $NAUTILUS_SCRIPT_SELECTED_URIS\n\nCurrent URI: $NAUTILUS_SCRIPT_CURRENT_URI\n\nWindow Geometry: $NAUTILUS_SCRIPT_WINDOW_GEOMETRY\n\nPositional Parameter \$\@: $@")

zenity --info --title="Nautilus Variables" --text="$TEXT"
