#!/bin/bash
#!/bin/bash
#: Title		: Identify iPod Ownher
#: Date			: 2010-05-12
#: Author		: "John Lehr" <slo.sleuth@gmail.com>
#: Version		: 1.0
#: Description	: A script to launch iPod_ID.sh as super user

gksu -u $USER "$HOME"/.gnome2/nautilus-scripts/.support_scripts/iPod_ID.sh
